export const Trainers: string[] = [
    "Ace Duo",
    "Ace Trainer",
    "Actor",
    "Actress",
    "Aether Foundation",
    "Aqua Admin",
    "Area Leader",
    "Aroma Lady",
    "Artist",
    "Artist Family",
    "Assistant",
    "Athlete",
    "Athletic Siblings",
    "Backers",
    "Backpacker",
    "Baker",
    "Bandana Guy",
    "Bandit",
    "Baron",
    "Baroness",
    "Battle Chatelaine",
    "Battle Girl",
    "Battle Legend",
    "Beauty",
    "Beginning Trainer",
    "Bellhop",
    "Big Star",
    "Biker",
    "Bird Keeper",
    "Black Belt",
    "Boarder",
    "Bodybuilder",
    "Boss Trainer",
    "Brains",
    "Bug Catcher",
    "Bug Maniac",
    "Bug Catching Man",
    "Burglar",
    "Butler",
    "Cabbie",
    "Café Master",
    "Cameraman",
    "Camper",
    "Casual Dude",
    "Casual Guy",
    "Celebrity",
    "Challenger",
    "Channeler",
    "Chaser",
    "Chef",
    "Chic Actress",
    "Child Star",
    "Cipher Admin",
    "Cipher Peon",
    "Clan Leader",
    "Close Siblings",
    "Clown",
    "Coach Trainer",
    "Colleagues",
    "Collector",
    "Colosseum Leader",
    "Colosseum Master",
    "Comedian",
    "Commander",
    "Cook",
    "Cool Beauty",
    "Countess",
    "Courier",
    "Cowgirl",
    "Crush Girl",
    "Crush Kin",
    "Curmudgeon",
    "Cute Maniac",
    "Cyclist",
    "Dancer",
    "Dancing Family",
    "Delinquent",
    "Doctor",
    "Double Team",
    "Dragon Tamer",
    "Driver",
    "Duchess",
    "Duke",
    "Earl",
    "Eevee users",
    "Electrifying Guy",
    "Elite Four",
    "Engineer",
    "Executive",
    "Expert",
    "Factory Head",
    "Fairy Tale Girl",
    "Fare Prince",
    "Fine Actor",
    "Firebreather",
    "Firefighter",
    "Fisher",
    "Free Diver",
    "Freshwoman",
    "Fun Old Man",
    "Furisode Girl",
    "Future Girl",
    "GAME FREAK",
    "Gardener",
    "Garçon",
    "Gentleman",
    "Girl In Love",
    "Girlfriend",
    "Glasses Man",
    "Glitch Trainer",
    "Golf Buddies",
    "Golfer",
    "Grand Duchess",
    "Grand Duke",
    "Guitarist",
    "Guy",
    "Gym Challenger",
    "Gym Leader",
    "Gym Trainer",
    "Hardheaded Girl",
    "Harlequin",
    "Haunted Man",
    "Hex Maniac",
    "High Tech Maniac",
    "Hiker",
    "Hiking Girl",
    "Honeymooners",
    "Hooligans",
    "Hoopster",
    "Hunter",
    "Icy Guy",
    "Idol",
    "Infielder",
    "Instructor",
    "Interviewers",
    "Island kahuna",
    "Janitor",
    "Joe Groupie",
    "Jogger",
    "Juggler",
    "Junior Representative",
    "Kantonian Gym",
    "Karate Family",
    "Kimono Girl",
    "Kindler",
    "Kitakami Ogre Clan",
    "Kruger Family",
    "Lady",
    "Lady in Suit",
    "Lass",
    "Leader in Training",
    "League Staff",
    "Linebacker",
    "Lone Wolf",
    "Lumiose Gang Member",
    "Macro Cosmos",
    "Madame",
    "Magician Apprentice",
    "Magma Admin",
    "Maid",
    "Marchioness",
    "Marquis",
    "Masked Man",
    "Masked Woman",
    "Master",
    "Master Class",
    "Master Dojo Student",
    "Master Representative",
    "Matron",
    "Medical Team",
    "Medium",
    "Miror B.Peon",
    "Model",
    "Monsieur",
    "Movie Star",
    "Mt BtlMaster",
    "Muddy Boy",
    "Music Crew",
    "Musician",
    "Mysterious Sisters",
    "Mystery Man",
    "Myth Trainer",
    "Navigator",
    "New Actress",
    "New Star",
    "Newscaster",
    "Ninja Boy",
    "Novice",
    "Nurse",
    "Nursery Aide"
];